#myName = input("What's your name?: ")
#print(myName)
#myAge = input("How old are you?: ")
#print(myAge)
#print("Gee, that's REALLY OLD")
#replit = input("Do you like Replit?")
#print("OF COURSE YOU DO!")

####################
#print("Definitely not a Phishing Scam")
#print()
#input("Your Name")
#print("Thanks for logging in")
#print(myName)
#cardNumber = input("What is your credit card number?")
#print("Thanks, I definitely wont put")
#print("cardNumber")
#print("into Amazon and order anything weird")
#print()
#print("Promise")
#maidenName = input("What is your Mother's maiden name? ")
#print()
#print("That's cool, I just wanted to know that")
#print(maidenName)
#print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

userName = input("What's your name?: ")
userFood = input("What's your favorite food?: ")
userMusic = input("What's your favorite music?: ")

print(userName + "'s favorite food is " + userFood + " and their favorite music is " + userMusic + ".")
